"""Laser g-code and SVG export.

Both are derived from the *stroke capture*: while `_cap_on` is set, the drawing
primitives record their stroked paths in board-grid (hole) units, and these exporters
serialize that. Both outputs are plain deterministic text, which makes them the easiest
thing in the library to pin down exactly.
"""

from __future__ import annotations

import pytest

from stripboard import StripBoard

PITCH_MM = 2.54


def captured(*, width=6, height="D", text="HI", **board_kwargs):
    """A LABEL render with stroke capture on -- what `project(gcode=...)` builds."""
    sb = StripBoard(page_width=12, page_height=10, black_and_white=True, **board_kwargs)
    sb._cap_on = True
    sb.begin_view("LABEL", width, height, at=(0, 0))
    sb.text(1, "A", text)
    sb.end_board()
    return sb


@pytest.fixture
def label_board():
    return captured()


def nc(board, tmp_path, **kwargs) -> list[str]:
    target = tmp_path / "out.nc"
    board.gen_gcode(target, **kwargs)
    return target.read_text(encoding="utf-8").splitlines()


# ---- capture ------------------------------------------------------------------------

def test_capture_records_paths_only_when_enabled():
    sb = StripBoard(page_width=12, page_height=10, black_and_white=True)
    sb.begin_view("LABEL", 6, "D", at=(0, 0))
    sb.text(1, "A", "HI")
    sb.end_board()
    assert sb._cap_paths == [], "nothing should be captured with _cap_on False"
    assert captured()._cap_paths, "captured paths expected with _cap_on True"


def test_export_without_a_capture_is_an_error(tmp_path):
    sb = StripBoard(page_width=12, page_height=10)
    with pytest.raises(ValueError, match="no captured geometry"):
        sb.gen_gcode(tmp_path / "empty.nc")


# ---- g-code preamble ----------------------------------------------------------------

def test_preamble_sets_metric_absolute_mode(label_board, tmp_path):
    lines = nc(label_board, tmp_path)
    assert lines[0].startswith("; GRBL laser g-code generated by stripboard")
    assert "G21" in lines[:8]      # millimetres
    assert "G90" in lines[:8]      # absolute coordinates
    assert lines[-2:] == ["M5", "G0 X0 Y0"], "must end with the laser off, back at origin"


def test_laser_mode_is_enabled_by_default(label_board, tmp_path):
    """$32=1 puts GRBL in laser mode; accepted at job start while it is still Idle."""
    assert "$32=1" in nc(label_board, tmp_path)


def test_laser_mode_can_be_suppressed(label_board, tmp_path):
    assert "$32=1" not in nc(label_board, tmp_path, laser_mode=False)


def test_dynamic_power_uses_m4_and_static_uses_m3(label_board, tmp_path):
    dyn = nc(label_board, tmp_path)
    assert any(ln.startswith("M4 S") for ln in dyn)
    assert not any(ln.startswith("M3 S") for ln in dyn)

    static = nc(label_board, tmp_path, dynamic=False)
    assert any(ln.startswith("M3 S") for ln in static)
    assert not any(ln.startswith("M4 S") for ln in static)


def test_power_and_feed_reach_the_output(label_board, tmp_path):
    lines = nc(label_board, tmp_path, power=420, feed=250)
    assert "M4 S420" in lines
    assert any(ln.endswith("F250") for ln in lines)


# ---- geometry -----------------------------------------------------------------------

def coords(lines) -> list[tuple[float, float]]:
    """Every engraved coordinate, in order.

    Skips the trailing `G0 X0 Y0` park move: it is a fixed return-to-origin, not
    transformed geometry, so including it would break the transform comparisons below.
    """
    out = []
    for ln in lines:
        if ln == "G0 X0 Y0":
            continue
        if ln.startswith(("G0 X", "G1 X")) and " Y" in ln:
            parts = ln.split()
            out.append((float(parts[1][1:]), float(parts[2][1:])))
    return out


def test_output_is_bbox_normalised_and_scaled_to_pitch(label_board, tmp_path):
    xs, ys = zip(*coords(nc(label_board, tmp_path)))
    assert min(xs) == 0.0 and min(ys) == 0.0, "geometry is shifted to the origin"
    # The stroked bounding box is the board outline, which spans (width+1) x (height+1)
    # holes -- so a 6-column, 4-row label measures 7 x 5 pitches.
    assert max(xs) == pytest.approx(7 * PITCH_MM, abs=1e-3)
    assert max(ys) == pytest.approx(5 * PITCH_MM, abs=1e-3)


def test_pitch_is_configurable(label_board, tmp_path):
    xs, _ = zip(*coords(nc(label_board, tmp_path, pitch_mm=5.08)))
    assert max(xs) == pytest.approx(7 * 5.08, abs=1e-3)


def test_origin_offsets_every_coordinate(label_board, tmp_path):
    base = coords(nc(label_board, tmp_path))
    moved = coords(nc(label_board, tmp_path, origin=(10.0, 20.0)))
    assert moved == [pytest.approx((x + 10.0, y + 20.0), abs=1e-3) for x, y in base]


def test_mirror_flips_x_within_the_bounding_box(label_board, tmp_path):
    base = coords(nc(label_board, tmp_path))
    mirrored = coords(nc(label_board, tmp_path, mirror=True))
    width = max(x for x, _ in base)
    assert [x for x, _ in mirrored] == [pytest.approx(width - x, abs=1e-3)
                                        for x, _ in base]


def test_flip_y_can_be_disabled(label_board, tmp_path):
    """Grid rows run top-down; laser Y runs bottom-up, so flip_y is on by default."""
    flipped = coords(nc(label_board, tmp_path))
    plain = coords(nc(label_board, tmp_path, flip_y=False))
    height = max(y for _, y in flipped)
    assert [y for _, y in plain] == [pytest.approx(height - y, abs=1e-3)
                                     for _, y in flipped]


def test_framing_pass_traces_the_bounding_box_at_low_power(label_board, tmp_path):
    lines = nc(label_board, tmp_path, power=1000, frame=True)
    assert "; --- framing pass (low power bounding box) ---" in lines
    assert "M3 S25" in lines, "framing runs at power // 40"


def test_passes_repeat_the_whole_engraving(label_board, tmp_path):
    once = nc(label_board, tmp_path)
    twice = nc(label_board, tmp_path, passes=3)
    burns_once = sum(1 for ln in once if ln.startswith("M4 S"))
    burns_thrice = sum(1 for ln in twice if ln.startswith("M4 S"))
    assert burns_thrice == 3 * burns_once


def test_gcode_is_deterministic(label_board, tmp_path):
    assert nc(label_board, tmp_path) == nc(label_board, tmp_path)


# ---- SVG ----------------------------------------------------------------------------

def test_svg_declares_millimetre_dimensions(label_board, tmp_path):
    target = tmp_path / "out.svg"
    label_board.gen_svg(target)
    svg = target.read_text(encoding="utf-8")
    assert svg.startswith("<svg xmlns=")
    assert f'width="{7 * PITCH_MM:.3f}mm"' in svg
    assert f'height="{5 * PITCH_MM:.3f}mm"' in svg
    assert svg.rstrip().endswith("</svg>")


def test_svg_has_one_polyline_per_captured_path(label_board, tmp_path):
    target = tmp_path / "out.svg"
    label_board.gen_svg(target)
    svg = target.read_text(encoding="utf-8")
    expected = len([p for p in label_board._cap_paths if len(p) >= 2])
    assert svg.count("<polyline") == expected


def test_svg_stroke_width_is_configurable(label_board, tmp_path):
    target = tmp_path / "out.svg"
    label_board.gen_svg(target, stroke_mm=0.4)
    assert 'stroke-width="0.4"' in target.read_text(encoding="utf-8")


# ---- file handling ------------------------------------------------------------------

@pytest.mark.parametrize("method", ["gen_gcode", "gen_svg"])
def test_exporters_create_missing_parent_directories(label_board, tmp_path, method):
    target = tmp_path / "deep" / "deeper" / f"out.{method[-2:]}"
    getattr(label_board, method)(target)
    assert target.exists()
