"""The 3D-printed carrier, generated by shelling out to OpenSCAD.

The tray a finished board slots into. Everything except the last step is testable without
OpenSCAD installed, because `gen_carrier` accepts an injected runner; the one test that
needs the real binary skips when it is absent.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from stripboard import StripBoard

HAS_OPENSCAD = shutil.which("openscad") is not None


@pytest.fixture
def sized_board():
    sb = StripBoard(page_width=30, page_height=36)
    sb.begin_board(18, "Z", title="T")
    return sb


def argv_for(board, **kwargs):
    captured = []
    board.gen_carrier("out.stl", runner=captured.append, **kwargs)
    return captured[0]


def flags(argv) -> dict[str, str]:
    """The `-D name=value` definitions, as a dict."""
    out = {}
    for i, token in enumerate(argv):
        if token == "-D":
            key, _, value = argv[i + 1].partition("=")
            out[key] = value
    return out


def test_board_dimensions_are_passed_to_the_scad_model(sized_board):
    d = flags(argv_for(sized_board))
    assert d["columns"] == "18"
    assert d["rows"] == "26"


def test_rotate_swaps_the_dimensions(sized_board):
    d = flags(argv_for(sized_board, rotate=True))
    assert d["columns"] == "26"
    assert d["rows"] == "18"


def test_stock_thickness_and_nozzle_are_configurable(sized_board):
    d = flags(argv_for(sized_board, board_thickness=1.2, nozzle=0.6))
    assert d["boardThickness"] == "1.2"
    assert d["nozzle"] == "0.6"


def test_the_scad_model_ships_with_the_package(sized_board):
    """It used to be referenced by an absolute path on one machine."""
    argv = argv_for(sized_board)
    scad = argv[1]
    assert scad.endswith("Carrier.scad")
    assert "stripboard/data" in scad.replace("\\", "/")


def test_arguments_are_a_list_not_a_split_string(sized_board):
    """Building the command by splitting a string breaks on paths containing spaces."""
    argv = argv_for(sized_board)
    assert isinstance(argv, list)
    assert argv[0] == "openscad"
    assert argv[-2] == "-o" and argv[-1] == "out.stl"


def test_a_missing_binary_raises_something_actionable(sized_board, monkeypatch):
    monkeypatch.setattr(shutil, "which", lambda _name: None)
    with pytest.raises(RuntimeError, match="needs the 'openscad' binary"):
        sized_board.gen_carrier("out.stl")


def test_a_failing_openscad_run_is_reported(sized_board, monkeypatch, tmp_path):
    monkeypatch.setattr(shutil, "which", lambda _name: "/usr/bin/openscad")

    def fake_run(argv, **kwargs):
        return subprocess.CompletedProcess(argv, 2, stdout="", stderr="ERROR: bad scad")

    monkeypatch.setattr(subprocess, "run", fake_run)
    with pytest.raises(RuntimeError, match=r"openscad failed \(exit 2\)"):
        sized_board.gen_carrier(tmp_path / "out.stl")


@pytest.mark.integration
@pytest.mark.skipif(not HAS_OPENSCAD, reason="needs the openscad binary")
def test_openscad_really_produces_an_stl(sized_board, tmp_path):
    target = sized_board.gen_carrier(tmp_path / "carrier.stl")
    assert target.exists()
    assert target.stat().st_size > 1000, "an STL this small is probably empty"
    assert target.read_bytes()[:5] == b"solid", "expected an ASCII STL"
