"""The state and behaviour `StripBoard`'s mixins share -- for type checking only.

`StripBoard` is composed from mixins that all operate on one board: they read and write
the same PDF document, the same transform stack, the same `show_*` toggles, the same
connection list. That is a real, intended coupling, but it means every mixin touches
attributes and methods it does not itself define, which a type checker cannot follow.

This class declares that shared surface. Mixins inherit it **under
``typing.TYPE_CHECKING`` only** -- at runtime they subclass ``object`` and nothing here
executes -- so the checker can resolve cross-mixin access while the runtime MRO is
exactly what it was before.

It doubles as documentation: 38 attributes and 65 methods
is the coupling, written down. Shrinking that list is how this would become a set of
collaborating objects rather than mixins.

Generated from what the mixins actually reference; regenerate if that set changes.
"""

from __future__ import annotations

from typing import Any

from .pdf import PdfDocument
from .transform import Matrix

__all__ = ["BoardState"]


class BoardState:
    """Shared board state and cross-mixin methods. Never instantiated."""

    # ---- state ----------------------------------------------------------------------
    _VIEW_PRESETS: dict[str, dict[str, bool]]
    _cap_ctm: list[Matrix]
    _cap_on: bool
    _cap_paths: list[list[tuple[float, float]]]
    _net_colors: dict[str, Any]
    _ref_counters: dict[str, int]
    _route_cache: dict[Any, Any]
    _route_components: list[Any]
    _route_edges: list[Any]
    _route_nets: list[Any]
    _router: Any
    black_and_white: bool
    board_height: int
    board_width: int
    colors: list[tuple[int, int, int]]
    connections: list[Any]
    flip_x: bool
    last_color: tuple[int, int, int]
    last_result: Any
    nc_points: list[Any]
    offset_x: float
    offset_y: float
    page_height: float
    page_width: float
    pdf: PdfDocument
    rotate: bool
    show_components: bool
    show_coordinates: bool
    show_crosses: bool
    show_drills: bool
    show_jumpers: bool
    show_numbers: bool
    show_strips: bool
    show_traces: bool
    trace_color: int
    trace_origins: list[Any]
    vector_chars: dict[str, list[list[float]]]
    wire_colors: dict[str, tuple[int, int, int]]

    # ---- methods defined in sibling mixins ------------------------------------------
    def _arc(self, x, y, rx, ry, f='S', tl=True, tr=True, bl=True, br=True) -> Any: ...
    def _as_ref(self, p) -> Any: ...
    def _build_problem(self) -> Any: ...
    def _cap_add(self, pts) -> Any: ...
    def _cap_bbox(self, kind) -> Any: ...
    def _cap_op(self, m_op) -> Any: ...
    def _cap_pt(self, x, y) -> Any: ...
    def _check_jumper_hole(self, x, y) -> Any: ...
    def _dip_pins(self, x, y, w, h, pins, upside_down, mod, skip_pins=None) -> Any: ...
    def _draw_big_button(self, x, y, emit=True) -> Any: ...
    def _draw_cap(self, x, y, l=1, upside_down=False, emit=True) -> Any: ...
    def _draw_diode(self, x, y, upside_down=False, len=1, emit=True) -> Any: ...
    def _draw_dip(self, x, y, w, h, name='', upside_down=False, pins=None, labels_inside=True, label_offset=0, label_scale=0.78, mod=1, skip_pins=None, emit=True) -> Any: ...
    def _draw_led(self, x, y, upside_down=False, len=1, weight=0.5, emit=True) -> Any: ...
    def _draw_resist(self, x, y, val='', upside_down=False, l=1, label_scale=1.0, emit=True) -> Any: ...
    def _draw_sip(self, x, y, l, name, upside_down=False, pins=None, flip=False, mod=1, width=1, label_scale=1.0, emit=True) -> Any: ...
    def _draw_terminal(self, x, y, h, mod=1, shroud_y_offset=0, emit=True) -> Any: ...
    def _ellipse(self, x, y, rx, ry, f='F', tl=True, tr=True, bl=True, br=True) -> Any: ...
    def _ensure_router(self) -> Any: ...
    def _flip_x(self) -> Any: ...
    def _flip_y(self) -> Any: ...
    def _line(self, x1, y1, x2, y2, f='S') -> Any: ...
    def _out(self, s) -> Any: ...
    def _pop(self) -> Any: ...
    def _push(self) -> Any: ...
    def _rect(self, x, y, w, h, f='S') -> Any: ...
    def _register(self, base, pinmap, origin, locked, keepouts=(), internal=(), redraw=None) -> Any: ...
    def _render_keepouts(self, instances, color=(255, 140, 0)) -> Any: ...
    def _render_routing(self, result, net_colors=None, show_cuts=True) -> Any: ...
    def _resolve_nets(self) -> Any: ...
    def _rotate(self, angle) -> Any: ...
    def _scale(self, scale_x, scale_y=None) -> Any: ...
    def _shade_rect(self, x, y, w, h, color=(255, 140, 0)) -> Any: ...
    def _signature(self, board, instances, netlist, seed, weights) -> Any: ...
    def _sip_pins(self, x, y, l, pins, upside_down, mod) -> Any: ...
    def _terminal_keepouts(self, x, y, h, shroud_y_offset) -> Any: ...
    def _translate(self, x, y) -> Any: ...
    def begin_board(self, board_width, board_height, rotate=False, at=(0, 0), show_strips=True, show_traces=True, show_numbers=False, show_crosses=True, show_jumpers=True, show_components=True, show_drills=True, show_coordinates=True, flip_x=False, title='') -> Any: ...
    def begin_view(self, view, board_width, board_height, *, at=(0, 0), title=None, rotate=False, **overrides) -> Any: ...
    def black(self) -> Any: ...
    def blue(self) -> Any: ...
    def box(self, x, y, w, h, f='S') -> Any: ...
    def color(self, r, g=0, b=0) -> Any: ...
    def cut(self, x, y, y2=None) -> Any: ...
    def dot(self, x, y, f='F') -> Any: ...
    def draw_letter(self, x, y, c, x_scale=1.0, y_scale=1.0) -> Any: ...
    def drill(self, x, y) -> Any: ...
    def end_board(self) -> Any: ...
    def grey(self, level=128) -> Any: ...
    def header(self, x, y, h) -> Any: ...
    def jdot(self, x, y, f='F') -> Any: ...
    def jumper(self, x, y, x2, y2, color='blue', show_length=True) -> Any: ...
    def line_width(self, w) -> Any: ...
    def polyline(self, poly, f='S') -> Any: ...
    def red(self) -> Any: ...
    def row(self, y) -> Any: ...
    def row_name(self, y) -> Any: ...
    def rtext(self, x, y, text, x_scale=1.0) -> Any: ...
    def text(self, x, y, text, x_scale=1.0) -> Any: ...
    def trace_jumper(self, x, y, x2, y2, color) -> Any: ...
    def trace_point(self, x, y, marked, color, first=False) -> Any: ...
    def utext(self, x, y, text) -> Any: ...
    def vtext(self, x, y, text, y_scale=1.0) -> Any: ...
    def white(self) -> Any: ...
    def wire(self, x, y, x2, y2) -> Any: ...
