"""Output formats: PDF, GRBL laser g-code, SVG, and an OpenSCAD carrier.

The g-code and SVG exporters consume the *stroke capture* rather than the PDF: while
`_cap_on` is set, the drawing primitives record their stroked paths in board-grid units,
and these serialize that to millimetres.
"""

from __future__ import annotations

import shutil
import subprocess
from importlib.resources import files
from pathlib import Path

__all__ = ["ExportMixin"]


class ExportMixin:
    def gen(self, pdf_name):
        """Write the board PDF to `pdf_name`, creating parent directories as needed."""
        return self.pdf.output(pdf_name)

    def gen_carrier(self, stl_name, board_thickness=1.7, nozzle=0.7, rotate=False,
                    runner=None):
        """Render a 3D-printable carrier for this board to `stl_name`, via OpenSCAD.

        The carrier is a shallow tray the finished board slots into. Sizing comes from
        the board's own dimensions plus the thickness of the stock and your printer's
        nozzle width.

        Requires the ``openscad`` binary on PATH, and the BOSL OpenSCAD library that
        ``Carrier.scad`` includes. `runner` replaces the subprocess call, for tests.

        Raises:
          RuntimeError: if openscad is missing, or exits non-zero.
        """
        board_width = self.board_width
        board_height = self.board_height
        if rotate:
            board_width, board_height = board_height, board_width

        scad = files("stripboard.data") / "Carrier.scad"
        argv = [
            "openscad", str(scad),
            "-D", f"columns={board_width}",
            "-D", f"rows={board_height}",
            "-D", f"boardThickness={board_thickness}",
            "-D", f"nozzle={nozzle}",
            "-o", str(stl_name),
        ]
        if runner is not None:
            return runner(argv)

        exe = shutil.which("openscad")
        if exe is None:
            raise RuntimeError(
                "gen_carrier() needs the 'openscad' binary on PATH. Install OpenSCAD "
                "(https://openscad.org) along with its BOSL library, or pass "
                "carrier=False."
            )
        argv[0] = exe

        target = Path(stl_name)
        if target.parent != Path():
            target.parent.mkdir(parents=True, exist_ok=True)

        proc = subprocess.run(argv, capture_output=True, text=True)
        if proc.returncode != 0:
            detail = (proc.stderr or proc.stdout or "").strip()
            raise RuntimeError(
                f"openscad failed (exit {proc.returncode}) building {stl_name}."
                + (f"\n{detail}" if detail else "")
            )
        return target

    def _cap_bbox(self, kind):
        """Return (paths, xmin, xmax, ymin, ymax) for the captured strokes, or raise."""
        paths = [p for p in self._cap_paths if len(p) >= 2]
        if not paths:
            raise ValueError(f"{kind}: no captured geometry -- "
                             "render a view with _cap_on=True first (see _gcode_render).")
        xs = [x for p in paths for x, _ in p]
        ys = [y for p in paths for _, y in p]
        return paths, min(xs), max(xs), min(ys), max(ys)

    def gen_gcode(self, name, *, power=1000, feed=700, passes=1, pitch_mm=2.54,
                  origin=(0.0, 0.0), mirror=False, flip_y=True, dynamic=True, frame=False,
                  laser_mode=True):
        """Write the captured LABEL strokes as GRBL laser g-code (mm) to `name`.

        Consumes ``self._cap_paths`` (filled while ``self._cap_on`` during a LABEL render;
        see :func:`_gcode_render`). Paths are in board-grid (hole) units; they are
        bbox-normalised, optionally X-mirrored (``mirror``, to etch the board flipped) and
        Y-flipped (``flip_y``: grid rows run top->down, laser Y runs bottom->up), scaled by
        ``pitch_mm`` (2.54 mm/hole), then offset by ``origin`` (mm). Emits M4 dynamic power
        (recommended for engraving) unless ``dynamic=False`` (M3), repeated ``passes`` times;
        ``frame=True`` traces the bounding box once at low power first for alignment.
        Unless ``laser_mode=False``, emits ``$32=1`` at the top so the controller enters
        GRBL laser mode automatically (accepted at job start while GRBL is Idle)."""
        paths, xmin, xmax, ymin, ymax = self._cap_bbox("gen_gcode")
        w = xmax - xmin

        def to_mm(pt):
            x, y = pt
            nx = (w - (x - xmin)) if mirror else (x - xmin)
            ny = (ymax - y) if flip_y else (y - ymin)
            return (nx * pitch_mm + origin[0], ny * pitch_mm + origin[1])

        mm_paths = [[to_mm(pt) for pt in p] for p in paths]
        on = "M4" if dynamic else "M3"
        lines = [
            "; GRBL laser g-code generated by stripboard",
            f"; power=S{power} feed={feed} passes={passes} pitch_mm={pitch_mm} "
            f"mirror={mirror} flip_y={flip_y} dynamic={dynamic} laser_mode={laser_mode}",
        ]
        if laser_mode:
            # Enable GRBL laser mode as part of the job. $-settings are accepted only while
            # GRBL is Idle, which it is here (before any motion). Persists to the controller.
            lines.append("$32=1")
        lines += ["G21", "G90", "G94", "M5", "S0"]

        if frame:
            (fx0, fy0), (fx1, fy1) = to_mm((xmin, ymin)), to_mm((xmax, ymax))
            lo, hi = min(fx0, fx1), max(fx0, fx1)
            blo, bhi = min(fy0, fy1), max(fy0, fy1)
            fp = max(1, power // 40)
            lines += ["; --- framing pass (low power bounding box) ---",
                      f"G0 X{lo:.3f} Y{blo:.3f}", f"M3 S{fp}",
                      f"G1 X{hi:.3f} Y{blo:.3f} F{feed}", f"G1 X{hi:.3f} Y{bhi:.3f}",
                      f"G1 X{lo:.3f} Y{bhi:.3f}", f"G1 X{lo:.3f} Y{blo:.3f}", "M5"]

        for _ in range(max(1, passes)):
            for p in mm_paths:
                x0, y0 = p[0]
                lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
                lines.append(f"{on} S{power}")
                lines.append(f"G1 X{p[1][0]:.3f} Y{p[1][1]:.3f} F{feed}")
                lines.extend(f"G1 X{x:.3f} Y{y:.3f}" for x, y in p[2:])
                lines.append("M5")

        lines += ["M5", "G0 X0 Y0"]
        target = Path(name)
        if target.parent != Path():
            target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {name}: {len(mm_paths)} paths, "
              f"{w*pitch_mm:.1f} x {(ymax-ymin)*pitch_mm:.1f} mm")

    def gen_svg(self, name, *, pitch_mm=2.54, stroke_mm=0.15):
        """Write the captured strokes as an SVG (mm) for vector import into LightBurn etc."""
        paths, xmin, xmax, ymin, ymax = self._cap_bbox("gen_svg")
        w, h = (xmax - xmin) * pitch_mm, (ymax - ymin) * pitch_mm

        def pt(p):
            return f"{(p[0]-xmin)*pitch_mm:.3f},{(ymax-p[1])*pitch_mm:.3f}"

        polys = "\n".join(f'  <polyline points="{" ".join(pt(q) for q in p)}"/>'
                          for p in paths)
        target = Path(name)
        if target.parent != Path():
            target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.3f}mm" '
            f'height="{h:.3f}mm" viewBox="0 0 {w:.3f} {h:.3f}">\n'
            f'<g fill="none" stroke="black" stroke-width="{stroke_mm}" '
            f'stroke-linecap="round" stroke-linejoin="round">\n{polys}\n</g>\n</svg>\n',
            encoding="utf-8")
        print(f"wrote {name}: {len(paths)} paths, {w:.1f} x {h:.1f} mm")
